questions =  [
    {"id": 0, "question": "The Bassfield/Soso Tornado was incorrectly assessed by the NWS and should have been EF5.", "effects": {"wee": 1}},
    {"id": 1, "question": "In most cases STP is a good way to evaulate tornado potenital", "effects": {"wee": .5, "inn": .5}},
    {"id": 2, "question": "The NWS should consider using DOW data when rating tornadoes", "effects": {"inn": 1}},
    {"id": 3, "question": "The NWS is doing a poor job with issuing tornado warnings", "effects": {"inn": .75, "wee": 1}},
    {"id": 4, "question": "The SPC should issue PDS Severe Tunderstorm watches with every event that could produce widespread 80mph gusts or widespedad 3 inch hail", {"inn": 1, "wee": .5}},
    {"id": 5, "question": "The National Weather Service needs more funding.", "effects": {"inn": 1.5}},
    {"id": 6, "question": "April 12th, 2020 deserved to be categorized as high risk.", "effects": {"wee": 1}},
    {"id": 7, "question": "El Reno was EF5 but didn't cause EF5 damage.", "effects": {"wee": 1}},
    {"id": 8, "question": "The National Weather Service should go back to the Fujita Scale.", "effects": {"inn": -1}},
    {"id": 9, "question": "The National Weather Service should consider using discord and should stop using nws chat.", "effects": {"inn": 1}},
    {"id": 10, "question": "The SPC should have not issued 60 sig on April 7th, 2006", "effects": {"wee": 1, "inn": -.25}},
    {"id": 11, "question": "Wx Twitter is full of weenies.", "effects": {"wee": -1}},
    {"id": 12, "question": "60 significant hail should be modified to high risk.", "effects": {"inn": 1}},
    {"id": 13, "question": "April 27th, 2011 was the worst tornado outbreak in modern times.", "effects": {"inn": 1, "wee": -1}},
    {"id": 14, "question": "The 1974 Super Outbreak was worse than April 27th, 2011", "effects": {"wee": -.25, "inn" -.70}},
    {"id": 15, "question": "The SPC should revamp the outlook catagories", "effects": {"inn": 1}},                       
    {"id": 16, "question": "Weather Youtube will never be good", "effects": {"wee": -1, "inn" -1}},
    {"id": 17, "question": "The TDS height and VROT method of evaulating tornadoes is the next big thing for radar anylsis", "effects": {"inn": 1}},
    {"id": 18, "question": "Self-taught mets can be just as effective as those who are degreed", "effects": {"wee": .5, "inn": .7}}, 
    {"id": 19, "question": "Backlash for 8/10/2020 not going high is warranted considering the expectations of 100mph gusts by 1630z", "effects": {"wee": 1}},
    {"id": 20, "question": "The reason for the record EF-5 drought is because past surveys overrated some of the F5's, thus EF-5's are more rare now becuase the surveys are better", "effects": {"inn": 1.2}},
    {"id": 21, "question": "Severe standards for warnings are too loose and should be changed to 2 inch hail or 70mph winds", "effects": {"inn": 1, "wee": 1}},                         
    {"id": 22, "question": "Storm chasing is a dangerous activity and should be reduced to only those highly skilled", "effects": {"inn": -.8, "wee": .5}}, 
    {"id": 23, "question": "Jarrel was likely only borderline EF-4 and was far overrated because of extreme slow movement of 5 mph", "effects": {"inn": -1, "wee": 1}},
    {"id": 24, "question": "El Reno-Piedmont 2011 was likely more intense than El Reno 2013 was", "effects": {"inn": -1.5, "wee": -.6}},
    {"id": 25, "question": "The weather community jumps to EF-5 way too much, and the ratings on most high end EF-4's are justified", "effects": {"inn": -1, "wee": -1}},
];
